### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [PonomarenkoSA/PonomarenkoSa.github.io#1]
Добрый день. Благодарю за проделанную работу. 
**Отлично**
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены
- в поле url реализованы все проверки (ip, dns, http/s)
В целом уровень работы очень достойный

К сожалению, текущая реализация содержит недостаток, не позволяющий мне засчитать ее на данной итерации.

Адрес сайта:
Валидацию не проходит следующий корректный адрес сайта
http://233.0.0.2:8080 - корректный IP

**Можно лучше** валидацию проходит следующий некорректный адрес сайта:
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)

**Comment by PonomarenkoSA** [comment]
Спасибо за замечания
Подготовлена новая версия

**Comment by zlocate** [comment]
Работа принята. Отлично! Желаю вас успехов в дальнейшем изучении курса
З.Ы Много времени ушло на написание такой навороченной регулярки для адреса сайта, покрывающей множество пересекающихся кейсов?

**Comment by PonomarenkoSA** [comment]
> Работа принята. Отлично! Желаю вас успехов в дальнейшем изучении курса
> З.Ы Много времени ушло на написание такой навороченной регулярки для адреса сайта, покрывающей множество пересекающихся кейсов?

Спасибо! Примерно 2 часа.
